FROM rgrenwick/lamp-baseline.2

# https://hub.docker.com/r/linode/lamp/
# MySQL Password: Admin2015
#---------------------------------------------------------------

## Step 1: Create the image
##   docker build -t nmea . 

## Step 2: Start the container
##   docker run -p 80:80 -p 3306:3306 -t -i nmea /bin/bash

## connect to mysql
## mysql -u root -pAdmin2015

#-------------------------------------------------------------------
#RUN apt-get install dmsetup && dmsetup mknodes

#RUN apt-get update && apt-get install -y apache2 && apt-get clean && rm -rf /var/lib/apt/lists/*

#COPY ./bin/etc /etc

RUN apt-get update

# install git
RUN apt-get install -y git

RUN apt-get install -y php5-mysql
RUN apt-get install -y openssh-server

# install Python 2
RUN apt-get install -y python
RUN apt-get install -y python-pip

# install python dependencies
RUN apt-get install -y python-mysqldb
RUN pip install pynmea2

# expose SSH
EXPOSE 22

# expose MySQL Port
EXPOSE 3306

# expose Apache port
EXPOSE 80

ENTRYPOINT /bin/bash